const welcome = "Welcome Back ";
const username = "Omotola1234";
const emailplaceholder = "Enter  Email";
const passwordplaceholder = "Enter  Password";
const show = "Show";
const forgottext = "Forgot Password?";
const usertext = "Not yet a user ? ";
const signup = " Sign Up";
const login = "Login";
